# This is a basic workflow that is manually triggered

# Display name of workflow
name: Basic Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # Display name for the job
    name: "Greetings, Program!"

    # The type of runner that the job will run on, in this case a Linus hosted runner
    runs-on:
      - ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs command(s) using the runners shell and gets context from the github object
      - name: Send greeting
        run: |
          echo "GITHUB_REF_VALUE: ${{GITHUB_REF}}"
          echo "Hello ${{ github.event.inputs.name }}" 
          echo "Your favorite city is ${{ github.event.inputs.city }}"
          echo "Is your favorite color blue: ${{ github.event.inputs.fav-color-blue }}"
